### ISSUE TITLE
Query by committe for Tic Tac Toe dataset

### ISSUE THREAD

**Issue by raghav-dalmia** [raghav-dalmia/Active_Learning#4]
train a classifier model with active learning algo for the tic tac toe dataset.

**Comment by shivanidalmia1203** [comment]
Hey I can help You with this !! @raghav-dalmia

**Comment by raghav-dalmia** [comment]
Thanks a lot @shivanidalmia1203.

**Comment by raghav-dalmia** [comment]
@shivanidalmia1203 can you please add outputs and references (papers) for the same code.
